In [1]:
#task1d
import numpy as np 

In [2]:
datafile = np.genfromtxt(r"C:/Users/akshi/Documents/C4_PYTHON/PRACTISE/DS1_C4_S1_AdmissionPredict_Data_Practice__1_ (1).csv",delimiter = ',',skip_header=1)
datafile

array([[  1.  , 337.  , 118.  , ...,   9.65,   1.  ,   0.92],
       [  2.  , 324.  , 107.  , ...,   8.87,   1.  ,   0.76],
       [  3.  , 316.  , 104.  , ...,   8.  ,   1.  ,   0.72],
       ...,
       [398.  , 330.  , 116.  , ...,   9.45,   1.  ,   0.91],
       [399.  , 312.  , 103.  , ...,   8.78,   0.  ,   0.67],
       [400.  , 333.  , 117.  , ...,   9.66,   1.  ,   0.95]])

In [3]:
#task2d
print(f"The GRE scores of all students are:")
datafile[:,1]

The GRE scores of all students are:


array([337., 324., 316., 322., 314., 330., 321., 308., 302., 323., 325.,
       327., 328., 307., 311., 314., 317., 319., 318., 303., 312., 325.,
       328., 334., 336., 340., 322., 298., 295., 310., 300., 327., 338.,
       340., 331., 320., 299., 300., 304., 307., 308., 316., 313., 332.,
       326., 322., 329., 339., 321., 327., 313., 312., 334., 324., 322.,
       320., 316., 298., 300., 311., 309., 307., 304., 315., 325., 325.,
       327., 316., 318., 328., 332., 336., 321., 314., 314., 329., 327.,
       301., 296., 294., 312., 340., 320., 322., 340., 319., 315., 317.,
       314., 316., 318., 299., 298., 301., 303., 304., 306., 331., 332.,
       323., 322., 312., 314., 317., 326., 316., 329., 338., 331., 304.,
       305., 321., 301., 320., 311., 310., 299., 290., 296., 327., 335.,
       334., 310., 308., 301., 300., 323., 319., 326., 333., 339., 303.,
       309., 323., 333., 314., 312., 316., 326., 318., 329., 332., 331.,
       340., 325., 320., 315., 326., 339., 311., 33

In [4]:
#task3d
score_GRE_greater = np.where(datafile[:,1] > 320)
print(score_GRE_greater)


(array([  0,   1,   3,   5,   6,   9,  10,  11,  12,  21,  22,  23,  24,
        25,  26,  31,  32,  33,  34,  43,  44,  45,  46,  47,  48,  49,
        52,  53,  54,  64,  65,  66,  69,  70,  71,  72,  75,  76,  81,
        83,  84,  97,  98,  99, 100, 104, 106, 107, 108, 111, 119, 120,
       121, 126, 128, 129, 130, 133, 134, 138, 140, 141, 142, 143, 144,
       147, 148, 150, 151, 152, 153, 154, 164, 165, 171, 172, 173, 174,
       176, 185, 187, 188, 189, 190, 191, 192, 193, 202, 203, 210, 211,
       212, 213, 214, 215, 216, 217, 218, 222, 229, 234, 235, 236, 237,
       242, 243, 245, 248, 249, 253, 254, 257, 258, 259, 260, 263, 264,
       268, 275, 276, 283, 284, 285, 286, 287, 298, 302, 303, 305, 306,
       307, 311, 318, 319, 321, 325, 328, 330, 335, 337, 338, 339, 341,
       351, 356, 359, 360, 361, 362, 365, 371, 372, 373, 380, 382, 384,
       385, 392, 394, 395, 396, 397, 399], dtype=int64),)


In [12]:
#task4
TOEFL = datafile[:,2]
chance_of_admit = datafile[:,8]
c = np.where(TOEFL > 110)
result = chance_of_admit[c]*100
result


array([92., 90., 84., 78., 70., 94., 95., 97., 94., 91., 90., 94., 87.,
       91., 86., 89., 78., 78., 72., 52., 55., 61., 78., 94., 96., 93.,
       72., 74., 96., 92., 94., 86., 90., 79., 74., 87., 91., 93., 94.,
       94., 85., 78., 84., 92., 96., 79., 89., 80., 90., 92., 97., 80.,
       81., 83., 96., 93., 94., 86., 81., 89., 89., 87., 85., 90., 89.,
       93., 93., 88., 90., 86., 94., 97., 97., 95., 96., 94., 93., 91.,
       76., 71., 82., 91., 88., 85., 86., 70., 76., 77., 93., 85., 90.,
       70., 83., 89., 80., 94., 93., 92., 89., 86., 90., 71., 80., 79.,
       80., 81., 80., 80., 83., 94., 93., 91., 86., 95., 96., 96., 84.,
       89., 91., 95.])

In [14]:
#task5
GRE = datafile[:,1]
TOEFL = datafile[:,2]
res = datafile[:,7]
condition = np.where((GRE>315) & (TOEFL>115) & (res == 1))
condition

(array([  0,  22,  23,  24,  25,  32,  52,  70,  81,  97,  98, 107, 108,
        120, 121, 129, 138, 141, 143, 148, 151, 171, 176, 187, 193, 202,
        203, 212, 213, 214, 215, 259, 285, 286, 325, 337, 361, 372, 385,
        397, 399], dtype=int64),)